### ISSUE TITLE
Chapter 3 - Figure 3.2 : RSS contour plot not symmetrical

### ISSUE THREAD

**Issue by JWarmenhoven** [JWarmenhoven/ISL-python#1]
What seems to be the problem with this plot? I think I created the meshgrid correctly, but it does not have the symmetrical shape as the one in the book.

<B>Python</B>
![fig3_2_python](https://cloud.githubusercontent.com/assets/7450204/8404277/f6530f9c-1e4b-11e5-98d5-51300b746425.png)

<B>ISL</B>
![fig3_2](https://cloud.githubusercontent.com/assets/7450204/8404250/bf7906de-1e4b-11e5-9b0a-6aac30683c0e.png)

I contacted Trevor Hastie to ask him about the R code for plot on the left. He was so kind to send me the following code. You will need to load the advertising data first and skip the first two lines and the last line.

```R
load("Chapter3.RData")
postscript(file="../Figs/leastsqexample1.ps",width=7,height=7,pointsize=14,horizontal=F)
set.seed(22)
par(mfrow=c(1,1),mar=c(5,5,2,2))
g=50
x=advertising$TV-mean(advertising$TV)
y=advertising$Sales
b=sum((x-mean(x))*(y-mean(y)))/sum((x-mean(x))^2)
a=mean(y)-b*mean(x)
RSS.min=sum((y-as.vector(cbind(1,x)%*%c(a,b)))^2)/100000
a.grid=seq(a-2,a+2,length=g)
b.grid=seq(b-.02,b+.02,length=g)
grid=as.matrix(expand.grid(a.grid,b.grid))

RSS=rep(0,g^2)
for (i in 1:(g^2)){
yhat=as.vector(cbind(1,x)%*%grid[i,])
RSS[i]=sum((y-yhat)^2)/1000
}
RSS=matrix(RSS,g,g)
m=which.min(RSS)

contour(a.grid-b*mean(advertising$TV),b.grid,RSS,xlab=expression(beta[0]),ylab=expression(beta[1]),levels=c(2.11,2.15,2.2,2.3,2.5,3),axes=T,frame.plot=T,col=4,drawlabels=T,cex.lab=1.5,labcex=1.3)

points(a-b*mean(advertising$TV),b,col=2,pch=19,cex=1.5)

dev.off()
```

**Comment by JWarmenhoven** [comment]
I think this is what is happening:
The text in the book describes the coefficients based on uncentered data (B0 = 7.03 and B1 = 0.0475), whereas the plot shows the model based on centered data (B0=14.02, B1=0.0475). The latter is visually more appealing for explaining the concept of a minimum RSS.
I think that, in order not to confuse the reader, the values on the axis of the B0 coefficients have been changed to correspond with the text.

**Comment by PiyushMishra** [comment]
why it computed x as  x=ads$TV-mean(ads$TV)?

**Comment by JWarmenhoven** [comment]
That is precisely the problem described in this issue If I remember correctly.

**Comment by jcsalaza69** [comment]
Thanks Mr. JWarmenhoven for clarify the issue. I had a hard time figuring out it. On the other hand, I made some calculations form the data without observations 1,2 and 200 and the values for the betas are B0=14.003 and B1=0.0477, respectively, they are slighly different to the ones you have here. Finally, I wonder if you can share the R code for the surface with the contour. Thanks

**Comment by JWarmenhoven** [comment]
I only have the code for the two dimensional contour plot on the left in figure 3.2 (see above), not the 3D plot.

**Comment by jcsalaza69** [comment]
Good morning Dr. JWarmenhoven, thank you for your help, you have a nice day

**Comment by jgh0208** [comment]
@JWarmenhoven  This is the code of the 3D plot!

persp(a.grid-b*mean(advertising$TV),b.grid,RSS,xlab=expression(beta[0]),ylab=expression(beta[1]),
      theta = 40,phi = 40,r=sqrt(3),d=1,scale = T,expand = 1,col = "white",border = NULL,ltheta = -135,
      lphi = 0,
      shade = NA,box = T,axes = T,nticks = 5,ticktype = "simple")
